name: Build Kivy APK

on: [push]  # يعمل عند كل رفع (push) للمستودع

jobs:
  build:
    runs-on: ubuntu-latest  # يستخدم خادم Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # يحمل ملفات المشروع

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # يستخدم Python 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip python3-pip zlib1g-dev

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug  # بناء APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk  # رفع APK كملف قابل للتنزيل
